#!/usr/bin/env python3
"""Train the per-bay occupancy classifier from device capture records and emit src/clf_model.h.

Input: a JSONL file; each line is one capture batch as the device POSTs it:
  {"device":..,"ts":..,"bays":[{"i":0,"label":0,"score":-1,"f":[<16 floats>], "y":1(optional)}]}
The training label is the per-bay "y" (hand-corrected) if present, else "label" (the device's
weak edge-engine decision). Trains an L2 logistic regression (standardized, class-balanced),
folds the scaler into raw-feature weights, and writes a clf_model.h whose clfPredict() consumes
the raw 16-float feature vector the firmware produces.
"""
import argparse, json, sys
import numpy as np

NFEAT = 16

def load_records(path):
    X, y = [], []
    with open(path) as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            try:
                obj = json.loads(line)
            except json.JSONDecodeError as e:
                print("warning: skipping malformed JSON line: %s" % e, file=sys.stderr)
                continue
            for bay in obj.get("cells", []):
                feat = bay.get("f")
                if not feat or len(feat) != NFEAT:
                    continue
                label = bay.get("y", bay.get("label"))
                if label is None:
                    continue
                X.append([float(v) for v in feat])
                y.append(int(label))
    return np.asarray(X, dtype=float), np.asarray(y, dtype=int)

def _fit_folded(feats, labels):
    """Fit StandardScaler+LogisticRegression; return raw-space (W[16], B)."""
    from sklearn.preprocessing import StandardScaler
    from sklearn.linear_model import LogisticRegression
    scaler = StandardScaler().fit(feats)
    clf = LogisticRegression(C=1.0, class_weight="balanced", max_iter=1000)
    clf.fit(scaler.transform(feats), labels)
    w = clf.coef_[0]; b = float(clf.intercept_[0])
    mean = scaler.mean_; std = scaler.scale_
    std = np.where(std == 0, 1.0, std)   # guard constant features
    # z = sum(w_i (x_i-mean_i)/std_i) + b = sum((w_i/std_i) x_i) + (b - sum(w_i mean_i/std_i))
    W = w / std
    B = b - float(np.sum(w * mean / std))
    return W, B

def emit_model_header(feats, labels, model_kind="logreg", out_path="../src/clf_model.h"):
    if model_kind != "logreg":
        raise ValueError("only 'logreg' export is supported")
    W, B = _fit_folded(feats, labels)
    wlist = ", ".join("%.8ef" % v for v in W)
    lines = [
        "#pragma once",
        "// Generated by tools/train_classifier.py — do not edit by hand.",
        "#include <math.h>",
        "#ifndef CLF_NFEAT",
        "#define CLF_NFEAT 16",
        "#endif",
        "#define CLF_MODEL_PRESENT 1",
        "// Occupied probability in [0,1] for a CLF_NFEAT-long raw feature vector.",
        "static inline float clfPredict(const float* feat) {",
        "  static const float W[16] = { %s };" % wlist,
        "  float z = %.8ef;" % B,
        "  for (int i = 0; i < 16; i++) z += W[i] * feat[i];",
        "  return 1.0f / (1.0f + expf(-z));",
        "}",
    ]
    with open(out_path, "w") as f:
        f.write("\n".join(lines) + "\n")
    return W, B

def _report(feats, labels):
    from sklearn.model_selection import train_test_split
    from sklearn.preprocessing import StandardScaler
    from sklearn.linear_model import LogisticRegression
    from sklearn.metrics import classification_report, confusion_matrix
    if len(set(labels.tolist())) < 2:
        print("[train] only one class present — cannot evaluate; training on all data.")
        return
    Xtr, Xte, ytr, yte = train_test_split(feats, labels, test_size=0.25,
                                          stratify=labels, random_state=0)
    sc = StandardScaler().fit(Xtr)
    clf = LogisticRegression(C=1.0, class_weight="balanced", max_iter=1000).fit(sc.transform(Xtr), ytr)
    yp = clf.predict(sc.transform(Xte))
    print("[train] held-out per-class report:")
    print(classification_report(yte, yp, target_names=["empty", "occupied"], zero_division=0))
    print("[train] confusion matrix [rows=true, cols=pred]:")
    print(confusion_matrix(yte, yp))

def main(argv=None):
    ap = argparse.ArgumentParser(description="Train occupancy classifier -> clf_model.h")
    ap.add_argument("--in", dest="inp", required=True, help="capture records (.jsonl)")
    ap.add_argument("--out", dest="out", default="../src/clf_model.h", help="output header path")
    args = ap.parse_args(argv)
    feats, labels = load_records(args.inp)
    if len(feats) == 0:
        print("no usable records in %s" % args.inp, file=sys.stderr); return 1
    print("[train] %d samples, %d occupied / %d empty" %
          (len(labels), int((labels == 1).sum()), int((labels == 0).sum())))
    _report(feats, labels)
    W, B = emit_model_header(feats, labels, "logreg", args.out)
    print("[train] wrote %s (logreg, %d features)" % (args.out, len(W)))
    return 0

if __name__ == "__main__":
    sys.exit(main())
