#pragma once
#include <stdint.h>

// Occupancy classifier. A model can be either compiled in (clf_model.h, generated by
// tools/train_classifier.py) or hot-swapped at runtime over the network into NVS,
// so retraining does not need a firmware rebuild. The runtime model takes priority.
// Both are the same logistic form: p = sigmoid(B + sum W[i]*feat[i]) with the scaler
// folded into raw-feature weights.

void  clfBegin();                  // load a runtime model from NVS (call once at boot)
bool  clfAvailable();              // true when a runtime OR embedded model is present
float clfScore(const float* feat); // occupied probability [0,1], or -1 if unavailable

// Runtime (hot-swappable) model management.
bool  clfRuntimePresent();                    // a runtime NVS model is loaded
bool  clfSaveRuntime(const float* w, float b); // validate + persist + activate (16 weights)
void  clfClearRuntime();                       // drop the runtime model (revert to embedded/edge)
