#pragma once
// Generated by tools/train_classifier.py — do not edit by hand. (Placeholder until a model is trained.)
#ifndef CLF_NFEAT
#define CLF_NFEAT 16
#endif
#define CLF_MODEL_PRESENT 0   // 1 once a real model is embedded; 0 = placeholder (firmware falls back to edge engine)
// Occupied probability in [0,1] for a CLF_NFEAT-long feature vector. The placeholder returns
// -1.0f and must not be trusted (always guard the call with CLF_MODEL_PRESENT).
static inline float clfPredict(const float* feat) { (void)feat; return -1.0f; }
